services:
  remarkable-pocket:
    image: ghcr.io/nov1n/remarkable-pocket:0.5.0
    restart: always
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - 65112:65112
    volumes:
      - ~/.remarkable-pocket:/root/.remarkable-pocket
      - ~/.rmapi:/root/.rmapi
      - ~/.rmapi-cache:/root/.cache/rmapi
    # Uncomment the line below to configure the application with additional command-line arguments.
    # This example increases the article limit to 15, and reduces the sync interval to 30 minutes.
    # command: ["-l", "15", "-i", "30m"]
